### PR TITLE
ENH: Update vtkOpenGL classes for OpenGL2 backend, add float uniform setting

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
@pieper Here is the modified version of CommonGL that I've been using.

One of the things that I did was add a rudimentary system for setting uniform variables on the vtkOpenGLShaderComputation object. (Only works with float currently)

There are a number of other changes as well, although I'm not sure how many of them are actually necessary. (Unfortunately my base OpenGL is not very good)

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
Hi @pieper, have you got a chance to look at this? Are there any changes that you think should be made?

**Comment by Sunderlandkyl** [comment]
@cpinter

**Comment by pieper** [comment]
Hi @Sunderlandkyl sorry I haven't had time to dig in and rebuild etc.  I'll try to get to it this afternoon.

**Comment by pieper** [comment]
Looks great - thanks!  I'll rebase this with Slicer and then test and commit.

**Comment by pieper** [comment]
Building on mac I still get the link errors related to the gl calls.

[ 17%] Linking CXX shared library ../../bin/libvtkAddon.dylib
Undefined symbols for architecture x86_64:
  "_glBindTexture", referenced from:
      vtkOpenGLTextureImage::UpdateTexture() in vtkOpenGLTextureImage.cxx.o
      vtkOpenGLTextureImage::Activate(unsigned int) in vtkOpenGLTextureImage.cxx.o
      vtkOpenGLTextureImage::AttachAsDrawTarget(int, int, int) in vtkOpenGLTextureImage.cxx.o
      vtkOpenGLTextureImage::ReadBack() in vtkOpenGLTextureImage.cxx.o
  "_glClear", referenced from:
      vtkOpenGLShaderComputation::AcquireResultRenderbuffer() in vtkOpenGLShaderComputation.cxx.o
  "_glClearColor", referenced from:
      vtkOpenGLShaderComputation::AcquireResultRenderbuffer() in vtkOpenGLShaderComputation.cxx.o
  "_glDeleteTextures", referenced from:
      vtkOpenGLTextureImage::UpdateTexture() in vtkOpenGLTextureImage.cxx.o
  "_glDisable", referenced from:
      vtkOpenGLTextureImage::AttachAsDrawTarget(int, int, int) in vtkOpenGLTextureImage.cxx.o
      vtkOpenGLShaderComputation::AcquireResultRenderbuffer() in vtkOpenGLShaderComputation.cxx.o
  "_glDrawArrays", referenced from:
      vtkOpenGLShaderComputation::Compute(float) in vtkOpenGLShaderComputation.cxx.o
  "_glEnable", referenced from:
      vtkOpenGLTextureImage::AttachAsDrawTarget(int, int, int) in vtkOpenGLTextureImage.cxx.o
      vtkOpenGLShaderComputation::AcquireResultRenderbuffer() in vtkOpenGLShaderComputation.cxx.o
  "_glGenTextures", referenced from:
      vtkOpenGLTextureImage::UpdateTexture() in vtkOpenGLTextureImage.cxx.o
  "_glGetTexImage", referenced from:
      vtkOpenGLTextureImage::ReadBack() in vtkOpenGLTextureImage.cxx.o
  "_glReadPixels", referenced from:
      vtkOpenGLShaderComputation::ReadResult() in vtkOpenGLShaderComputation.cxx.o
  "_glTexParameteri", referenced from:
      vtkOpenGLTextureImage::UpdateTexture() in vtkOpenGLTextureImage.cxx.o
  "_glViewport", referenced from:
      vtkOpenGLTextureImage::AttachAsDrawTarget(int, int, int) in vtkOpenGLTextureImage.cxx.o
      vtkOpenGLShaderComputation::AcquireResultRenderbuffer() in vtkOpenGLShaderComputation.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libvtkAddon.dylib] Error 1
make[1]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Built target MRMLCoreHierarchy
make: *** [all] Error 2

**Comment by Sunderlandkyl** [comment]
Interesting. I've been building on Mac, using a mostly up to date version of Slicer.
I'll take a look again and see if there are any other potential differences.

**Comment by pieper** [comment]
Are you testing with a Qt5 build?

It's odd because these aren't even the same symbols that used to need the vtkgl namespace.

**Comment by Sunderlandkyl** [comment]
Yeah, according to my build scripts, it should be a Qt 5.9, VTK 9 build.

**Comment by pieper** [comment]
I'm using Qt 5.10 and the VTKv9 from the current Slicer master with mac os 10.13.6

I checked the makefile and the OpenGL framework is on the link line.

**Comment by pieper** [comment]
I've looked around and tried some options but I'm not seeing why these symbols aren't defined while others seem to link okay.  Let me know how your build goes.

**Comment by Sunderlandkyl** [comment]
I just put the files in an updated build on Mac and got the same errors.

The other build that I have been using, and that does compile fine hasn't been rebased on the master since June 16th.

I'll keep looking and see what I can turn up.

**Comment by pieper** [comment]
Thanks @Sunderlandkyl  - if I have time I'll try adding the classes directly in my vtk build.  If needed as a workaround we could commit them to Slicer/VTK.

**Comment by pieper** [comment]
@Sunderlandkyl did you have any further thoughts on how to address this?  I'm thinking we could try building it as a [VTK remote module](https://github.com/Kitware/VTK/tree/master/Remote) and even contributing it to VTK that way.

**Comment by Sunderlandkyl** [comment]
Unfortunately no, I wasn't able to figure anything out. I'm currently attempting to compile the classes on an updated Windows build to see if it's a Mac only issue.

Adding the shader classes as a remote module seems like a great idea.

**Comment by pieper** [comment]
I just tested and adding the classes directly to the VTKv9/Rendering directory works.  So there's something weird going on when OpenGL is linked at the Slicer level.

**Comment by Sunderlandkyl** [comment]
I can confirm that the linking issue happens on Windows as well.

**Comment by pieper** [comment]
That's interesting - thanks for checking.

Looks like it's something to do with glew and vtkOpenGLState or other fairly recent changes in VTK.

**Comment by pieper** [comment]
@Sunderlandkyl did you have any other ideas about this?  I think the vtk remote module idea is the best I can come up with - it looks like a little work to set up, but should be doable and it would resolve the linking issues (or if they came up again it would be easier for other people to help debug).

**Comment by Sunderlandkyl** [comment]
No, I haven't had any further ideas.
The vtk remote module seems like a good solution to me.

Would you like me to work at setting it up, or is that something that you could do easier?

**Comment by pieper** [comment]
I'd be happy if you set it up - I think the easiest might be to start with
an existing one and rename the parts as needed.  The documentation seemed
straightforward but there are a number of elements that need to follow the
exact structure.

**Comment by Sunderlandkyl** [comment]
So, when I tried to set up the remote module, I ended up having the same linking issues as before.

I did some more digging and was able to find a fix for the issue in Slicer.
The linked libs in vtkAddon was previously:
~~~
set(libs
  ${VTK_LIBRARIES}
  )
~~~
But works when you add OPENGL_gl_LIBRARY, which on Windows evaluates to opengl32:
~~~
set(libs
  ${VTK_LIBRARIES}
  ${OPENGL_gl_LIBRARY}
  )
~~~

I'm going to test to see if this fix works on Mac as well.
If it ends up working, do you want to integrate these classes in Slicer or as a VTK remote module?

**Comment by Sunderlandkyl** [comment]
The previous fix does not work on Mac.

This one however works on both Mac and PC:
~~~
find_package(OpenGL)
set(libs
  ${VTK_LIBRARIES}
  ${OPENGL_LIBRARIES}
  )
~~~

**Comment by cpinter** [comment]
You mean it works on Linux and Windows but not on Mac?

**Comment by Sunderlandkyl** [comment]
The last one that I posted works on Windows and Mac. I haven't tested it on Linux.

**Comment by pieper** [comment]
Awesome work Kyle!  (Sorry I didn't read this yesterday when it came in - I was anticipating more debugging required but was overjoyed to know it's a solution instead 👍 ).

Yes, let's put this in vtkAddons for now at least so that it's in Slicer with no extra delays.  Then we can decide if it it goes in vtk proper or a remote module at our leisure.

I could test on linux before merging if you think there's a risk it won't work, but it looks like it will work.

**Comment by pieper** [comment]
I finally had a chance to test this on linux and everything worked as expected.

So I committed this to the master.  Thanks again @Sunderlandkyl for the fix 👏 

https://github.com/Slicer/Slicer/commit/16a4878de6f17f097618cfb4472cb209538bf82c

**Pull request merged**
